id: ID4EA7AE2
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T23:09:29.311158'
last_modified: '2022-05-30T23:09:29.311164'
parser: null
source_metadata:
  title: Shakya Shri Series
  language: zh
  description: 'Texts by the great yogi Tokden Shakya Shri (rtogs ldan shākya shrī,
    1853–1919):'
  volume:
    f2331:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      base_file: f2331.txt
      order: 1
      parent: Guru Yoga
    fFC0B:
      title: Supplication to Lord Mila Shepa Dorje
      base_file: fFC0B.txt
      order: 2
      parent: Prayers
    f59C8:
      title: 'The Shower of Blessings: A Prayer'
      base_file: f59C8.txt
      order: 3
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
